name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3.3.0
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=%23FE6E96&color_dots=%23EEF2F6,%2377A7D3,%23306998,%23255271,%231C3E57
            dist/github-snake-dark.svg?color_snake=%23306998&color_dots=%230D1117,%23F49FBA,%23FE6E96,%23DB5B7F,%23C5365F
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations for dark/light mode adaptive display
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
